import type { Metadata } from 'next';
import { LocaleProvider } from './context/LocaleContext';
import { Oswald } from 'next/font/google';
import '../styles/globals.css';
import { UIProvider } from '@/context';

const oswald = Oswald({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <LocaleProvider>
      <UIProvider>
        <html lang='en'>
          <body className={oswald.className}>{children}</body>
        </html>
      </UIProvider>
    </LocaleProvider>
  );
}
