import type { Metadata } from 'next';
import { LocaleProvider } from './context/LocaleContext';
import { Oswald } from 'next/font/google';
import '../styles/globals.css';

const oswald = Oswald({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <LocaleProvider>
      <html lang='en'>
        <body className={oswald.className}>{children}</body>
      </html>
    </LocaleProvider>
  );
}
